### ISSUE TITLE
checkSystem: make sure it always runs, if bash is missing or Node has incorrect version

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#404]
* [x] if bash is not on the system, it errors out. checkSystem does not seem to open its dialog
* [x] double check that if node version < 12, checkSystem also shows a warning

```
[DBUX exec] > c:\Users\b07902131\.vscode\extensions\domi.dbux-code-0.3.14\dist$ where.exe where.exe
[DBUX exec] > c:\Users\b07902131\.vscode\extensions\domi.dbux-code-0.3.14\dist$ which which
[DBUX which] whichWhich: C:\Windows\System32\where.exe
[DBUX exec] > c:\Users\b07902131\.vscode\extensions\domi.dbux-code-0.3.14\dist$ C:\Windows\System32\where.exe volta
[DBUX which] Couldn't find volta in $PATH. Got code 1 when executing "C:\Windows\System32\where.exe volta"
[DBUX terminalWrapper] wrapping terminal command:  {"cwd":"c:\\Users\\b07902131\\.vscode\\extensions\\domi.dbux-code-0.3.14","command":"npm install --only=prod && npm i @dbux/cli@0.3.14","tmpFolder":"C:/Users/B07902~1/AppData/Local/Temp/dbux-sRYj66"} pathToDbuxRun: c:/Users/b07902131/.vscode/extensions/domi.dbux-code-0.3.14/dist/_dbux_run.js
[DBUX exec] > c:\Users\b07902131\.vscode\extensions\domi.dbux-code-0.3.14\dist$ C:\Windows\System32\where.exe bash
[DBUX which] Couldn't find bash in $PATH. Got code 1 when executing "C:\Windows\System32\where.exe bash"
[DBUX ProgressBarTask] Error when executing function of task (anonymous callback) - TypeError: Terminal command failed: Cannot read property '0' of null

  command $ c:\Users\b07902131\.vscode\extensions\domi.dbux-code-0.3.14$ npm install --only=prod && npm i @dbux/cli@0.3.14
	at h (c:\Users\b07902131\.vscode\extensions\domi.dbux-code-0.3.14\dist\bundle.js:2:349020)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async TerminalWrapper_TerminalWrapper._run (c:\Users\b07902131\.vscode\extensions\domi.dbux-code-0.3.14\dist\bundle.js:2:134394)
	at async ProjectsManager_ProjectsManager.execInTerminal (c:\Users\b07902131\.vscode\extensions\domi.dbux-code-0.3.14\dist\bundle.js:2:130857)
	at async ProjectsManager_ProjectsManager._doInstallModules (c:\Users\b07902131\.vscode\extensions\domi.dbux-code-0.3.14\dist\bundle.js:2:130677)
	at async ProjectsManager_ProjectsManager.installDbuxDependencies (c:\Users\b07902131\.vscode\extensions\domi.dbux-code-0.3.14\dist\bundle.js:2:130358)
	at async ProjectsManager_ProjectsManager.installDependencies (c:\Users\b07902131\.vscode\extensions\domi.dbux-code-0.3.14\dist\bundle.js:2:129839)
	at async Kt.e.hasInstalledSharedDependencies.Object.cancellable (c:\Users\b07902131\.vscode\extensions\domi.dbux-code-0.3.14\dist\bundle.js:2:501306)
	at async c:\Users\b07902131\.vscode\extensions\domi.dbux-code-0.3.14\dist\bundle.js:2:196914
```

**Comment by Domiii** [comment]
* [ ] if bash is not on the system, it errors out. checkSystem does not seem to open its dialog
* [ ] double check that if node version < 12, checkSystem also shows a warning

* [ ] prepare some slides on dealing with issues related to system settings, since system problems seem to be the most common problems (Domi)
