### ISSUE TITLE
Cannot focus on selected trace TypeError: Cannot read property 'resultCallId' of undefined

### ISSUE THREAD

**Issue by edisonhello** [Domiii/dbux#415]
When running `fibonacci.js` and clicks on call graph.

```
[DBUX FocusController] Cannot focus on selected trace TypeError: Cannot read property 'resultCallId' of undefined
	at isCallResult (/home/edison/Coding/dbux/dbux-code/dist/bundle.js:694:17)
	at getCallerTraceOfTrace (/home/edison/Coding/dbux/dbux-code/dist/bundle.js:5104:113)
	at ContextNode.setSelected (/home/edison/Coding/dbux/dbux-code/dist/bundle.js:10337:299)
	at FocusController._selectContextNode (/home/edison/Coding/dbux/dbux-code/dist/bundle.js:11355:33)
	at /home/edison/Coding/dbux/dbux-code/dist/bundle.js:11341:14
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by MiccWan** [comment]
Can't reproduce
