### ISSUE TITLE
`TypeError: Cannot read property 'staticTraceId' of undefined` when executing `producer_consumer_async.js` with `runFile`

### ISSUE THREAD

**Issue by MiccWan** [Domiii/dbux#428]
## Reproduce

Use `Dbux: Run current file` button to run `producer_consumer_async.js`

## Error Log

```
Dbux command failed: TypeError: Cannot read property 'staticTraceId' of undefined
    at StaticTraceCollection.getStaticTraceId (E:\works\dbux\dbux\dbux-runtime\dist\index.js:3637:24)
        -> E:\works\dbux\dbux\dbux-runtime\dist\file:\E:\works\dbux\dbux\dbux-runtime\src\data\staticTraceCollection.js:68:24        
    at TraceCollection._trace (E:\works\dbux\dbux\dbux-runtime\dist\index.js:3715:90)
        -> E:\works\dbux\dbux\dbux-runtime\dist\file:\E:\works\dbux\dbux\dbux-runtime\src\data\traceCollection.js:55:49
    at TraceCollection.traceWithResultValue (E:\works\dbux\dbux\dbux-runtime\dist\index.js:3683:24)
        -> E:\works\dbux\dbux\dbux-runtime\dist\file:\E:\works\dbux\dbux\dbux-runtime\src\data\traceCollection.js:23:24
    at RuntimeMonitor.traceExpression (E:\works\dbux\dbux\dbux-runtime\dist\index.js:2529:210)
        -> E:\works\dbux\dbux\dbux-runtime\dist\file:\E:\works\dbux\dbux\dbux-runtime\src\RuntimeMonitor.js:372:37
    at ProgramMonitor.traceExpr (E:\works\dbux\dbux\dbux-runtime\dist\index.js:1424:33)
        -> E:\works\dbux\dbux\dbux-runtime\dist\file:\E:\works\dbux\dbux\dbux-runtime\src\ProgramMonitor.js:144:33
    at new ProducerBase (e:\works\dbux\dbux\samples\case-studies\async\producer_consumer\producer_consumer_base.js:84:29)
        -> e:\works\dbux\dbux\samples\case-studies\async\producer_consumer\producer_consumer_base.js:66:17
    at new Producer (e:\works\dbux\dbux\samples\case-studies\async\producer_consumer\producer_consumer_async.js:37:86)
        -> e:\works\dbux\dbux\samples\case-studies\async\producer_consumer\producer_consumer_async.js:37:37
    at Object.<anonymous> (e:\works\dbux\dbux\samples\case-studies\async\producer_consumer\producer_consumer_async.js:58:106)        
        -> e:\works\dbux\dbux\samples\case-studies\async\producer_consumer\producer_consumer_async.js:58:1
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module._compile (E:\works\dbux\dbux\node_modules\pirates\lib\index.js:99:24)
exiting...
[dbux-runtime] Process exiting but not all data has been sent out. Analysis will be incomplete. This is probably a crash or you called `process.exit` manually.
```

**Comment by Domiii** [comment]
Problem comes from the fact that Babel might sometimes inject new functions to wrap existing `staticTraces` which then have the incorrect `staticContext`. 

[The `constructor2` sample](https://github.com/Domiii/dbux/commit/2a6f2a4bf16e3d066aeca35e561c16d1fac00698#diff-850ca1a7e3d1d67b7f5e2b1e3913181d4d5368be52e6f8c6f71c949bb6aeed57) partially examplifies the problem (however does not reproduce the bug, as it only involves a single program).

In the following code, given `A` is in `A.js` and `B` is in `B.js`, Babel will inject a new `A.constructor` and moves all initial class assignments into it, like so: `this.f = () => {}; this.x = 1;`, and that ctor is not Dbux-instrumented. As a result, Dbux would think that those assignments then belongs to `B.js` because it looked up `programId` by the last context on the stack which is `B.js` (where we called `new B();`).

```js
// A.js
class A { f = () => {}; x = 1; }

// B.js
class B extends A { }

new B();
```

## Solution

For the assignments `f = () => {};` and `x = 1;`, we now have the correct `programId` (which fixes this bug), but the assignments still have the wrong `contextId`. Also, there is some issue with the sourcemaps for `A.f`, when calling it.
